spring:
  application:
    name: order
  datasource:
    username: root
    password: zhangke12289
    url: jdbc:mysql://180.76.172.198/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 180.76.172.198
    port: 5672
    username: guest
    password: guest
env:
  dev
